sudo: false
language: node_js
node_js:
- '4'
- '5'
- '6'
after_success:
- make coveralls
- '[[ -n "$TRAVIS_TAG" ]] && make gh-pages'
deploy:
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: lkRl7d7WwlI6UEnnNJbfyOsOYQyUsIFXulD8Fff8HSKFgr39Ye5eObS3u69+zdTeYaQfOJ0fl4XD/kAe3coUJHN3fN7GPfz+sxmCYybiYa35ZaX9lMojzeyP4jccfaJldMP+ucpk3+d2zG5iigx493CWKpMZR83zyMBXU8BWEvo=
  on:
    tags: true
    node: '6'
    repo: Dreamscapes/semantic-merge
    all_branches: true
env:
  global:
    secure: uFp6OOCdUo4KOD6IFmK240pDSLJ1/fn2cAgsuK3wRYLUZ9zQL2l8nE5P7/MkmE+Kfoycf4iWKpv55W55EzQ3EULbah/oE0uSKrYDuRSN1EUL3t5WiiR+XMiKGnAWi4y2cmjxsQ0oRe9JVIgWVENi+tF8mYfU02HCEv71DJ/bsa4=
